
required = [
  "github.com/client9/misspell/cmd/misspell",
  "golang.org/x/tools/cmd/goimports",
  "github.com/golang/dep/cmd/dep",
]

[[constraint]]
  name = "golang.org/x/tools"
  revision = "4c874b978acba4ecd4a257d3bb8829dd5de17be8"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
