apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: prettier
spec:
  parameters:
  - name: ORGANIZATION
  - name: REPOSITORY
  - name: ASSIGNEE
    default: mattmoor

  steps:
  - name: prettier
    image: gcr.io/convoy-adapter/prettier
    # We override the entrypoint of the ko image to embed shell functionality.
    command: ["/bin/sh", "-c"]
    args: ["prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)"]

  - name: open-pull-request
    image: github.com/mattmoor/knobots/cmd/pr-builder
    args:
    - "-organization=${ORGANIZATION}"
    - "-repository=${REPOSITORY}"
    - "-title=Format markdown"
    - "-body"
    - |
        Produced via:
          `prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)`
        /assign @${ASSIGNEE}
    env:
    - name: GITHUB_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-comment-secret
          key: accessToken
    - name: GITHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: github-comment-secret
          key: username
    # Inject the generated pod name so that we can use it as a
    # pseudo-random branch name (and associate open PRs with
    # build logs).
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
